

const DHT = "DHT";
const LED = "LED";
const PAN = "PAN";
const BUTTONFLOOR = "BUTTONFLOOR";
const MANUALLY = "MANUALLY";
const FLAME = "FLAME";
const DISTANCE = "DISTANCE";
module.exports = {DHT,LED, PAN ,MANUALLY,FLAME,DISTANCE,BUTTONFLOOR};
